SauChatRoom/SauChatRoom/Controllers/RoomModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SauChatRoom.Models.ContextModels;

namespace SauChatRoom.Controllers
{
    public class RoomModelsController : Controller
    {
        private ChatRoomContext db = new ChatRoomContext();

        // GET: RoomModels
        public ActionResult Index()
        {
            return View(db.dbRoom.ToList());
        }

        // GET: RoomModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModel roomModel = db.dbRoom.Find(id);
            if (roomModel == null)
            {
                return HttpNotFound();
            }
            return View(roomModel);
        }

        // GET: RoomModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RoomModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoomID,photo,RoomName,CreateDate,modifiedDate")] RoomModel roomModel)
        {
            if (ModelState.IsValid)
            {
                db.dbRoom.Add(roomModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(roomModel);
        }

        // GET: RoomModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModel roomModel = db.dbRoom.Find(id);
            if (roomModel == null)
            {
                return HttpNotFound();
            }
            return View(roomModel);
        }

        // POST: RoomModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoomID,photo,RoomName,CreateDate,modifiedDate")] RoomModel roomModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roomModel);
        }

        // GET: RoomModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModel roomModel = db.dbRoom.Find(id);
            if (roomModel == null)
            {
                return HttpNotFound();
            }
            return View(roomModel);
        }

        // POST: RoomModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RoomModel roomModel = db.dbRoom.Find(id);
            db.dbRoom.Remove(roomModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SauChatRoom/SauChatRoom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Saü Chat Room </title>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
             
                <div class="navbar-collapse collapse">
                    @if (this.User.IsInRole("Administrator"))
                    {

                        <div class="navbar-header">
                            @Html.ActionLink("Saü Chat Room", "IndexAdmin", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        </div>
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Admin", "IndexPanel", "Admin")</li>
                        </ul>
                    }
                    else
                    {   <div class="navbar-header">
                        @Html.ActionLink("Saü Chat Room", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>

                    }

                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer1">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 ">
                        <!-- widgets column center -->
                        <ul class="list-unstyled clear-margins">
                            <!-- widgets -->
                            <li class="widget-container widget_recent_news">
                                <!-- widgets list -->
                                <h1 class="title-widget">İletisim </h1>
                                <div class="footerp">
                                    <p><b>E-mail:</b> <a href="mailto:oguzhan.kocabas1@ogr.sakarya.edu.tr">oguzhan.kocabas1@ogr.sakarya.edu.tr</a></p>
                                    <p><b>Okul No: </b>G151210309, </p>
                                    <p><b>GSM No: </b>5076487375 </p>
                                </div>

                                <div class="social-icons ">

                                    <ul class="nomargin">
                                        <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook-square fa-3x social-fb" id="social"></i></a>
                                        <a href="https://twitter.com/ "target="_blank"><i class="fa fa-twitter-square fa-3x social-tw" id="social"></i></a>
                                        <a href="https://plus.google.com/" target="_blank"><i class="fa fa-google-plus-square fa-3x social-gp" id="social"></i></a>
                                        <a href="mailto:oguzhan.kocabas1@ogr.sakarya.edu.tr" target="_blank"><i class="fa fa-envelope-square fa-3x social-em" id="social"></i></a>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="copyright" style="text-align:center">
                        © 2016, Oğuzhan Kocabaş, Tüm Hakları Saklıdır.

                    </div>
                </div>

            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SauChatRoom/SauChatRoom/Views/Shared/_LayoutAdmin.cshtml
<!doctype html>
<html lang="en" class="no-js">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/Content/AdminCss/reset.css"> <!-- CSS reset -->
    <link rel="stylesheet" href="~/Content/AdminCss/style.css"> <!-- Resource style -->
    <script src="../Scripts/modernizr.js"></script> <!-- Modernizr -->

    <title>Responsive Sidebar Navigation | CodyHouse</title>
</head>
<body>

    <header class="cd-main-header">
        @if (this.User.IsInRole("Administrator"))
        {

            <div class="navbar-header">
                @Html.ActionLink("Saü Chat Room", "IndexAdmin", "Home", new { area = "" }, new { @class = "cd-logo" })
            </div>
        }
        else
        {   <div class="navbar-header">
        @Html.ActionLink("Saü Chat Room", "Index", "Home", new { area = "" }, new { @class = "cd-logo" })
    </div>
        }
        <a href="#0" class="cd-nav-trigger">Menu<span></span></a>
        <nav class="cd-nav">
            <ul class="cd-top-nav">
                <li>
                    @using Microsoft.AspNet.Identity
                    @if (Request.IsAuthenticated)
                    {
                        using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "" }))
                        {
                            @Html.AntiForgeryToken()


                            <a href="javascript:document.getElementById('logoutForm').submit()">Çıkış</a>

                        }
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                            <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                        </ul>
                    }
                </li>
            </ul>
        </nav>
    </header> <!-- .cd-main-header -->
    <main class="cd-main-content">
        <nav class="cd-side-nav">
            <ul>
                <li class="cd-label">Main</li>
                <li class="overview">
                <li>@Html.ActionLink("Oda Yönetimi", "Index", "RoomModels", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                <li class="notifications active">
                <li>@Html.ActionLink("Rol Yönetimi", "RolYonetimIndex", "Admin", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
            </ul>
        </nav>
    </main> <!-- .cd-main-content -->
    <div class="content-wrapper">

        @RenderBody()
    </div>

    <script src="../Scripts/jquery-2.1.4.js"></script>
    <script src="../Scripts/jquery.menu-aim.js"></script>
    <script src="../Scripts/main.js"></script> <!-- Resource jQuery -->
</body>
</html>